[package]
name = "api-dzengi-rs"
version = "0.1.0"
edition = "2024"

[features]

[dependencies]
tokio = { version = "^1" }
uuid = { version = "^1", features = ["serde"] }
serde = { version = "^1", features = ["derive"] }
serde_json = { version = "^1" }
validator = { version = "^0.20", features = ["derive"] }
strum_macros = "^0.27"
strum = { version = "^0.27", features = ["derive"] }
