#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum RejectReason {
    AccountNotFound,
    ClosedMarket,
    CloseOnly,
    EngineBusy,
    HedgingModeGsl,
    InstrumentNotAvailable,
    InstrumentNotFound,
    InvalidOrder,
    InvalidOrderQty,
    InvalidPrice,
    LongOnly,
    OffMarket,
    OrderNotFound,
    OriginalGslUpdate,
    PositionNotFound,
    RcInstrumentClientNop,
    RcInstrumentEloBaLowp,
    RcNotEnoughMargin,
    RcNotFound,
    RcNoDates,
    RcSettlement,
    RcUnknown,
    RequiredGsl,
    RiskCheck,
    Throttling,
    Unknown,
}
