use crate::auto_import_models;

auto_import_models! {
    cancel_order_request,
    account_info_request,
    recv_window_request,
    deposit_address_request,
    deposits_request,
    depth_request,
    fetch_order_request,
    klines_request,
    ledger_request,
    leverage_settings_request,
    my_trades_request,
    open_orders_request,
    symbol_request,
    agg_trades_request,
    trading_positions_history_request,
    transactions_request,
    withdrawals_request,
    close_trading_position_request,
    create_order_request,
    update_trading_order_request,
    update_trading_position_request,
    change_order_request,
}
